#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

status=0
files=$(git diff --diff-filter=d --cached --name-only | grep -E 'materialscoord.*\.(py)$' | sed '/test_/d')
files=`echo $files | tr '\n' ' '`
pycodestyle materialscoord $files 2> /dev/null
if [ $? -ne 0 ]; then
  echo "Bad code style detected by pycodestyle. Fix before commit."
  exit 1
fi
flake8 materialscoord $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by flake8. Fix before commit."
  exit 1
fi
pydocstyle --match='(?!test_).*\.py' materialscoord $files
if [ $? -ne 0 ]; then
  echo "Bad doc style detected. Fix before commit."
  exit 1
fi
